version: '2'
services:
  websocket:
    image: registry.live247.ai:443/websocket:latest
    restart: always
    hostname: websocket
    container_name: websocket
    ports:
      - "7145:7145"
    extra_hosts:
      - "influx_server kafka_broker sensor_consumer alerta redis_server postgres mysql:10.0.0.5"
    environment:
      - "REDIS_SECURE:sOmE_sEcUrE_pAsS"
      - "REDIS_PORT:6379"
      - "INFLUX_PORT:8080"
      - "NODEBACKEND_PORT:7145"


