version: '2'
services:
 nodelive247:
    image: registry.live247.ai:443/nodelive247:latest
    restart: always
    hostname: chatlive247
    container_name: chatlive247
    ports:
      - "7125:7125"
    extra_hosts:
      - "influx_server kafka_broker sensor_consumer alerta redis_server postgres mysql:10.0.0.10"
    environment:
      - "REDIS_SECURE:sOmE_sEcUrE_pAsS"
      - "REDIS_PORT:6379"
      - "INFLUX_PORT:8080"
      - "NODEBACKEND_PORT:7125"


