version: '2'
services:
 react-web-app:
    image: vuphamterra/live247-emr-react-webapp
    restart: always
    hostname: uilive247
    container_name: react-web-app
    ports:
      - "7141:7141"
    extra_hosts:
      - "postgres mysql:10.0.0.10"
    environment:
            - REACT_APP_PRODUCTION_API_URL=/api


