version: "3.5"

volumes:
  local_redis_data: {}

services:
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    restart: always
    ports:
      - "3306:3306"
    container_name: mysql_emr
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: live247_emr
      MYSQL_PASSWORD: takeitthenyouaredog2104@#
      MYSQL_DATABASE: openemr
    volumes:
      - ./data:/docker-entrypoint-initdb.d